NUMPY


In [5]:
import numpy as np

In [7]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [9]:
print(arr)

[1 2 3 4 5]


In [11]:
print(type(arr))

<class 'numpy.ndarray'>


In [13]:
arr

array([1, 2, 3, 4, 5])

In [17]:
print(arr.shape)

(5,)


In [19]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [21]:
arr.shape

(3, 5)

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [30]:
#check the shape of the array
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

# INDEXING

In [51]:
arr = np.array([1,2,3,4,5])

In [45]:
arr[3]

4

In [57]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]
arr = np.array([my_lst1,my_lst2,my_lst3])

In [63]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [71]:
arr[0:2,0:3]

array([[1, 2, 3],
       [2, 3, 4]])

In [73]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [77]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [79]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [87]:
arr1 = np.arange(0,10)

In [89]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr2 = np.arange(0,10,2)

In [97]:
arr2

array([0, 2, 4, 6, 8])

In [103]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# COPYING

In [143]:
arr1 = np.array([1,2,3,4,5])

In [171]:
arr1

array([  1,   2,   3, 100, 100])

In [167]:
arr2 = arr1.copy()

In [169]:
print(arr1)
arr2[3:] = 100
print(arr2)

[  1   2   3 100 100]
[  1   2   3 100 100]


In [163]:
id(arr1)

2265118232368

In [165]:
id(arr1)

2265118232368

In [173]:
kj = np.array([1,2,3,4,5])

In [175]:
kj

array([1, 2, 3, 4, 5])

In [177]:
kj2 = kj.copy()

In [181]:
kj2[3:] = 100

In [183]:
kj2

array([  1,   2,   3, 100, 100])

In [185]:
print(kj)

[1 2 3 4 5]


In [193]:
kj<3

array([ True,  True, False, False, False])

In [189]:
kj[kj<3]

array([1, 2])

In [191]:
kj*2

array([ 2,  4,  6,  8, 10])

In [203]:
np.ones((3,5),dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])