# PANDAS

#### PANDAS is open source.BSD licesned library providing high high perfomance ,easy to use data structure and data analytics tools for the python
##### what is data frame?
##### data series?
##### different operation in pandas

In [78]:
import pandas as pd
import numpy as np

In [80]:
# playing with data 
df = pd.DataFrame(np.arange(0,20).reshape(5,4),index = ['ROW1','ROW2','ROW3','ROW4','ROW5'],columns = ['COLUMN1','COLUMN2','COLUMN3','COLUMN4'])



'''pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
)'''

In [83]:
df.head()

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [85]:
df.to_csv('Test1.csv')

In [ ]:
type(df)
# dataframe should have more than one row and column
# but in dataseries i should have only one row or one column

In [96]:
type(df)


pandas.core.frame.DataFrame

### accessing the element
### 1.loc 2.iloc

In [104]:
df.loc["ROW1"]

COLUMN1    0
COLUMN2    1
COLUMN3    2
COLUMN4    3
Name: ROW1, dtype: int32

In [106]:
type(df.loc["ROW1"])

pandas.core.series.Series

In [112]:
df.iloc[0:2,0:3]

COLUMN1  COLUMN2  COLUMN3
ROW1        0        1        2
ROW2        4        5        6

In [114]:
type(df.iloc[0:2,0:3])

pandas.core.frame.DataFrame

### converting dataframe into array

In [119]:
df.iloc[:,:].values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [137]:
 ar = df.iloc[:,:].values.shape

In [141]:
 ar1 = df.iloc[:,:].values.reshape(4,5)

In [135]:
df.iloc[:,:].values.shape

(5, 4)

In [139]:
ar

(5, 4)

In [143]:
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [147]:
ar1.shape

(4, 5)

In [149]:
df.isnull()

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1    False    False    False    False
ROW2    False    False    False    False
ROW3    False    False    False    False
ROW4    False    False    False    False
ROW5    False    False    False    False

In [151]:
df.isnull().sum()

COLUMN1    0
COLUMN2    0
COLUMN3    0
COLUMN4    0
dtype: int64

### to count how many number are present

In [158]:
df['COLUMN1'].value_counts()

COLUMN1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [166]:
df['COLUMN1'].unique()
# if element was repeating it does not print

array([ 0,  4,  8, 12, 16])

In [170]:
df[['COLUMN1','COLUMN2']]

COLUMN1  COLUMN2
ROW1        0        1
ROW2        4        5
ROW3        8        9
ROW4       12       13
ROW5       16       17